name: Hello Action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Check out
      uses: actions/checkout@v2
    - name: Run Hello script
      run: python hello.py
